### PR TITLE
Add dynamic field localisation

### PR DESCRIPTION
**Pull request by cxkoda**
This adds `Field` localisation in a dynamic `BucketStorage` bundle

- - -
This change is [Reviewable](https://reviewable.io/reviews/proofxyz/solidify/5)

### CODE REVIEW

**Review by aschlosberg — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/proofxyz/solidify/5)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @cxkoda)

___
*[`contracts/BucketStorageLib.sol` line 118 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA-1FM1-wPL5V2w2f6:-NJA-1FM1-wPL5V2w2f7:b7zlygt) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/contracts/BucketStorageLib.sol#L118)):*
> ```Solidity
>             uint256 numFields_ = bundle[storageId].numFields();
> 
>             if (fieldId < numFields_) {
> ```

Counting down instead of up was very confusing and took me a while to figure out. Can you introduce a new `uint256` counter?
___
*[`contracts/BucketStorageLib.sol` line 131 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA-Fya6eYop4599hbS:-NJA-Fya6eYop4599hbT:b-8a05gs) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/contracts/BucketStorageLib.sol#L131)):*
> ```Solidity
>                 break;
>             }
>             fieldId -= numFieldsPerBucket[bucketId];
> ```

As above
___
*[`test/indexed/IndexedBuckets.t.sol` line 88 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA0C6B31l3YQ_LhUW8:-NJA0C6B31l3YQ_LhUW9:b6e556n) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/test/indexed/IndexedBuckets.t.sol#L88)):*
> ```Solidity
> 
>     function testLocateByFieldGroups() public {
>         assertLocation(0, 0, 0, 0, 0);
> ```

I don't understand how to interpret these. What's the "rule"?
___
*[`test/indexed/IndexedBuckets.t.sol` line 103 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA-oqj3lNomGzJad_Y:-NJA-oqj3lNomGzJad_Z:bj41szh) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/test/indexed/IndexedBuckets.t.sol#L103)):*
> ```Solidity
>         uint256 wantFieldId
>     ) public {
>         uint256[] memory fieldGroupSizes = new uint256[](3);
> ```

Can you move the construction of `coords` into `testLocateByFieldGroups()` and pass it in to `assertLocation()`? The code then reads as "this is the state you're dealing with, now these are the assertions" whereas currently it's back to front.

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/proofxyz/solidify/5)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @aschlosberg)

___
*[`contracts/BucketStorageLib.sol` line 118 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA-1FM1-wPL5V2w2f6:-NJA4L7p4RcRzi_FeRcc:bljm4nf) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/contracts/BucketStorageLib.sol#L118)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Counting down instead of up was very confusing and took me a while to figure out. Can you introduce a new `uint256` counter?
</blockquote></details>

Implemented it by counting up a separate variable. To me it seems more complicated to understand now. But I think I am just biased towards the previous one since I spent more time with it. So I'll let you make the call.
___
*[`contracts/BucketStorageLib.sol` line 131 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA-Fya6eYop4599hbS:-NJA4KwQCxds302u8NLD:b-896fix) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/contracts/BucketStorageLib.sol#L131)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

As above
</blockquote></details>

Done.
___
*[`test/indexed/IndexedBuckets.t.sol` line 88 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA0C6B31l3YQ_LhUW8:-NJA3ynF87dyl_EXww-n:balmj0m) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/test/indexed/IndexedBuckets.t.sol#L88)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

I don't understand how to interpret these. What's the "rule"?
</blockquote></details>

Thanks for catching this. It's named wrongly since `assertLocation` should be the test implementation. Renamed it to `_testLocateByFieldGroupAndIndex`.
___
*[`test/indexed/IndexedBuckets.t.sol` line 103 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA-oqj3lNomGzJad_Y:-NJA4BPA62GBA54I9xHo:b-34vmyd) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/test/indexed/IndexedBuckets.t.sol#L103)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Can you move the construction of `coords` into `testLocateByFieldGroups()` and pass it in to `assertLocation()`? The code then reads as "this is the state you're dealing with, now these are the assertions" whereas currently it's back to front.
</blockquote></details>

See above

**Review by aschlosberg — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/proofxyz/solidify/5)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @cxkoda)

___
*[`contracts/BucketStorageLib.sol` line 118 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA-1FM1-wPL5V2w2f6:-NJA6lwLDeKT3Xnz6SFu:byscc4v) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/contracts/BucketStorageLib.sol#L118)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Implemented it by counting up a separate variable. To me it seems more complicated to understand now. But I think I am just biased towards the previous one since I spent more time with it. So I'll let you make the call.
</blockquote></details>

I didn't realise that you'd have to add the final subtraction, which makes the original cleaner. Sorry, feel free to undo it.

I think if you name the argument `absoluteFieldId` and create a variable, `localFieldId` that you decrement then it's a bit clearer.
___
*[`test/indexed/IndexedBuckets.t.sol` line 88 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA0C6B31l3YQ_LhUW8:-NJAASmr75nVImp-3DjA:b5he0k5) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/test/indexed/IndexedBuckets.t.sol#L88)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Thanks for catching this. It's named wrongly since `assertLocation` should be the test implementation. Renamed it to `_testLocateByFieldGroupAndIndex`.
</blockquote></details>

Please add something like the following:

```
Test data are the same as for testFieldAccess(), where bucket IDs are foo=0, bar=1, and qux=2
```

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/proofxyz/solidify/5)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @aschlosberg)

___
*[`contracts/BucketStorageLib.sol` line 118 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA-1FM1-wPL5V2w2f6:-NJAHmLV2CZtOU26l2up:b-896fix) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/contracts/BucketStorageLib.sol#L118)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

I didn't realise that you'd have to add the final subtraction, which makes the original cleaner. Sorry, feel free to undo it.

I think if you name the argument `absoluteFieldId` and create a variable, `localFieldId` that you decrement then it's a bit clearer.
</blockquote></details>

Done.
___
*[`test/indexed/IndexedBuckets.t.sol` line 88 at r1](https://reviewable.io/reviews/proofxyz/solidify/5#-NJA0C6B31l3YQ_LhUW8:-NJAHGtjCyXRnZRllz3K:b-q36imc) ([raw file](https://github.com/proofxyz/solidify/blob/fa0d1d47415802b05a605bf8da5ea0842cf13905/test/indexed/IndexedBuckets.t.sol#L88)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Please add something like the following:

```
Test data are the same as for testFieldAccess(), where bucket IDs are foo=0, bar=1, and qux=2
```
</blockquote></details>

I moved this into an own test setup with stubbed bucket storages.

**Review by aschlosberg — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/proofxyz/solidify/5)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @cxkoda)

___
*[`test/BucketStorageLib.t.sol` line 119 at r4](https://reviewable.io/reviews/proofxyz/solidify/5#-NJAMeXCBfVcGC9sOALS:-NJAMeXCBfVcGC9sOALT:b-lwybzq) ([raw file](https://github.com/proofxyz/solidify/blob/e62643041242160517ba6cb6d2157965ece8407d/test/BucketStorageLib.t.sol#L119)):*
> ```Solidity
>     }
> 
>     function _testLocateByFieldGroupAndIndex(
> ```

If you put this above `testLocateByFieldGroups()` then you don't need the comment explaining the `3,5,2,1`.

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/proofxyz/solidify/5)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @aschlosberg)

___
*[`test/BucketStorageLib.t.sol` line 119 at r4](https://reviewable.io/reviews/proofxyz/solidify/5#-NJAMeXCBfVcGC9sOALS:-NJAPjeO7bOZ5J8gflcF:b-896fix) ([raw file](https://github.com/proofxyz/solidify/blob/e62643041242160517ba6cb6d2157965ece8407d/test/BucketStorageLib.t.sol#L119)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

If you put this above `testLocateByFieldGroups()` then you don't need the comment explaining the `3,5,2,1`.
</blockquote></details>

Done.

**Pull request merged**
